theme = "catppuccin_latte_transparent"

[editor]
line-number = "relative"
rulers = [120]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
"C-s" = ":write" 
"C-t" = "save_selection" # Save the current selection to the jumplist
"C-k" = "expand_selection"
"C-j" = "shrink_selection"
"C-h" = "select_prev_sibling"
"C-l" = "select_next_sibling"
"C-d" = ["page_cursor_half_down", "goto_window_center"]
"C-u" = ["page_cursor_half_up", "goto_window_center"]
"C-z" = "repeat_last_motion"
"C-g" = ":reset-diff-change"

[keys.normal.space]
"l" = "toggle_line_comments"
"A-c" = "no_op"
# Search
"*" = "search_selection"

# create a new minor mode bound to `+` as a temp replacement for alt key
[keys.normal."+"]
# Shell
"|" = "shell_pipe_to"
"!" = "shell_append_output"
# Selection
"s" = "split_selection_on_newline"
"-" = "merge_selections"
"_" = "merge_consecutive_selections"
";" = "flip_selections"
":" = "ensure_selections_forward"
"," = "remove_primary_selection"
"C" = "copy_selection_on_prev_line"
"(" = "rotate_selection_contents_backward"
")" = "rotate_selection_contents_forward"
"x" = "shrink_to_line_bounds"
"J" = "join_selections_space"
"K" = "remove_selections"
"a" = "select_all_siblings"
"I" = "select_all_children"
"e" = "move_parent_node_end"
"b" = "move_parent_node_start"
# Changes
"d" = "delete_selection_noyank"  
"c" = "change_selection_noyank"  
"´" = "switch_to_uppercase"
"u" = "earlier"
"U" = "later"


[keys.insert]
"C-s" = ":write" # overwrites jumplist to check
# up = "no_op"
# down = "no_op"
# left = "no_op"
# right = "no_op"
# pageup = "no_op"
# pagedown = "no_op"
# home = "no_op"
# end = "no_op"
